#!/usr/bin/env python3
"""Rasterize Geist Mono (Vercel's monospace) into an embedded grayscale glyph
atlas for the kernel framebuffer console. The kernel is no_std and cannot
rasterize a TTF at runtime, so we pre-render printable ASCII (0x20..0x7e) at a
fixed cell size and emit a Rust source file holding the coverage bytes.

Each glyph is CELL_W*CELL_H bytes, row-major, 0 = background .. 255 = full ink,
so the renderer can alpha-blend fg/bg per pixel (antialiased text).

Run:  python3 tools/fonts/gen_geist.py
Out:  kernel/src/font_geist.rs
"""
import sys
from PIL import Image, ImageDraw, ImageFont

TTF = "assets/GeistMono-Regular.ttf"
SIZE = 16
OUT = "kernel/src/font_geist.rs"
FIRST, LAST = 0x20, 0x7e

font = ImageFont.truetype(TTF, SIZE)
advance = round(font.getlength("M"))
ascent, descent = font.getmetrics()
CELL_W = advance
CELL_H = ascent + descent
N = LAST - FIRST + 1

glyphs = []
for code in range(FIRST, LAST + 1):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    # anchor "la" = left / ascender: pen at top-left, glyph fills [0, ascent+descent]
    d.text((0, 0), chr(code), font=font, fill=255, anchor="la")
    glyphs.append(list(img.getdata()))

with open(OUT, "w") as f:
    f.write("//! AUTO-GENERATED by tools/fonts/gen_geist.py from Geist Mono\n")
    f.write("//! (Vercel, OFL). Do not edit by hand -- rerun the generator.\n")
    f.write("//!\n")
    f.write("//! Printable ASCII 0x20..=0x7e rasterized at a fixed cell, one byte of\n")
    f.write("//! grayscale coverage per pixel (0 = background .. 255 = full ink) so the\n")
    f.write("//! framebuffer console can alpha-blend fg/bg for antialiased text.\n\n")
    f.write(f"pub const CELL_W: usize = {CELL_W};\n")
    f.write(f"pub const CELL_H: usize = {CELL_H};\n")
    f.write(f"pub const FIRST: u8 = {FIRST:#04x};\n")
    f.write(f"pub const LAST: u8 = {LAST:#04x};\n\n")
    f.write("/// Coverage for each printable ASCII glyph, row-major `CELL_W*CELL_H`.\n")
    f.write(f"pub static GLYPHS: [[u8; {CELL_W * CELL_H}]; {N}] = [\n")
    for code, data in zip(range(FIRST, LAST + 1), glyphs):
        ch = chr(code) if code != 0x5c else "backslash"
        vals = ",".join(str(v) for v in data)
        f.write(f"    [{vals}], // {code:#04x} {ch!r}\n" if code != 0x5c
                else f"    [{vals}], // 0x5c backslash\n")
    f.write("];\n")

print(f"wrote {OUT}: {N} glyphs, cell {CELL_W}x{CELL_H}")
