[build]
target = "../targets/x86_64-chitti.json"
rustflags = ["-C", "link-arg=-Tlinker.ld"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

[target.x86_64-chitti]
runner = "../xtask/run-test-in-qemu.sh"
