#!/usr/bin/env python3
"""Generate the embedded Mozilla CA trust store for the in-kernel TLS verifier.

Fetches (or reads) the curl/Mozilla `cacert.pem` bundle, decodes each PEM
CERTIFICATE to DER, and emits:
  * kernel/src/net/ca_roots.der  — all root certs concatenated (one blob,
    `include_bytes!`-ed so it compiles fast; not committed-by-hand).
  * kernel/src/net/ca_roots.rs   — the span index + provenance header.

Authoritative-source rule (like gen_cabac_tables / gen_iq_tables): the trust
anchors come verbatim from Mozilla's published bundle, never hand-edited. The
kernel validator (`net::x509`) treats each entry as a trust anchor: matches an
issuer DN and provides the SPKI to verify the certificate signed by it.

Usage:
    curl -sLO https://curl.se/ca/cacert.pem
    python3 tools/gen_ca_roots.py cacert.pem
"""
import base64
import hashlib
import re
import sys
import os

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "cacert.pem"
    pem = open(src, "rb").read().decode("latin-1")
    blocks = re.findall(r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", pem, re.S)
    if not blocks:
        raise SystemExit("no CERTIFICATE blocks found")
    ders = [base64.b64decode("".join(b.split())) for b in blocks]

    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    der_path = os.path.join(root, "kernel/src/net/ca_roots.der")
    rs_path = os.path.join(root, "kernel/src/net/ca_roots.rs")

    blob = b"".join(ders)
    with open(der_path, "wb") as f:
        f.write(blob)

    spans = []
    off = 0
    for d in ders:
        spans.append((off, len(d)))
        off += len(d)

    digest = hashlib.sha256(blob).hexdigest()
    out = []
    out.append("//! Embedded Mozilla CA trust store, GENERATED by tools/gen_ca_roots.py")
    out.append("//! from the curl/Mozilla `cacert.pem` bundle — do not edit by hand.")
    out.append(f"//! {len(ders)} root certificates, {len(blob)} bytes DER total.")
    out.append(f"//! bundle sha256: {digest}")
    out.append("#![allow(clippy::all)]")
    out.append("")
    out.append("/// All root certificates concatenated (DER).")
    out.append('pub static CA_ROOTS_DER: &[u8] = include_bytes!("ca_roots.der");')
    out.append("")
    out.append("/// `(offset, len)` of each root within [`CA_ROOTS_DER`].")
    out.append(f"pub static CA_ROOT_SPANS: [(u32, u32); {len(spans)}] = [")
    for (o, l) in spans:
        out.append(f"    ({o}, {l}),")
    out.append("];")
    out.append("")
    out.append("/// Iterate each root's DER slice.")
    out.append("pub fn roots() -> impl Iterator<Item = &'static [u8]> {")
    out.append("    CA_ROOT_SPANS.iter().map(|&(o, l)| &CA_ROOTS_DER[o as usize..(o + l) as usize])")
    out.append("}")
    out.append("")
    with open(rs_path, "w") as f:
        f.write("\n".join(out))

    print(f"wrote {der_path} ({len(blob)} bytes, {len(ders)} roots)")
    print(f"wrote {rs_path}")


if __name__ == "__main__":
    main()
