#!/bin/sh
# Regenerate kernel/src/net/rsa_testvec.rs — an RSA-2048 known-answer vector
# (PKCS#1 v1.5 + PSS SHA-256 signatures over "hello world") for net::rsa tests.
set -e
tmp=$(mktemp -d)
openssl genrsa -out "$tmp/k.pem" 2048 2>/dev/null
printf 'hello world' > "$tmp/msg.txt"
openssl rsa -in "$tmp/k.pem" -RSAPublicKey_out -outform DER -out "$tmp/pub.der" 2>/dev/null
openssl dgst -sha256 -sign "$tmp/k.pem" -out "$tmp/pkcs1.bin" "$tmp/msg.txt"
openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:32 \
  -sign "$tmp/k.pem" -out "$tmp/pss.bin" "$tmp/msg.txt"
python3 - "$tmp" <<'PY'
import sys
t=sys.argv[1]
def a(n,p): return f"const {n}: &[u8] = &[{','.join(str(b) for b in open(p,'rb').read())}];\n"
o="// GENERATED by tools/gen_rsa_testvec.sh — RSA-2048 KAT for net::rsa tests.\n"
o+=a("RSA_PUB_PKCS1",f"{t}/pub.der")+a("RSA_SIG_PKCS1",f"{t}/pkcs1.bin")+a("RSA_SIG_PSS",f"{t}/pss.bin")
open("kernel/src/net/rsa_testvec.rs","w").write(o)
PY
rm -rf "$tmp"
echo "wrote kernel/src/net/rsa_testvec.rs"
