#!/bin/sh
# Regenerate kernel/src/net/ca_testvec.rs — a real cert chain (leaf +
# intermediates) fetched from a public host, for net::x509 path-validation
# tests. TEST_NOW must be a fixed unix time inside the leaf's validity window.
set -e
HOST=${1:-example.com}
tmp=$(mktemp -d)
echo | openssl s_client -connect "$HOST:443" -servername "$HOST" -showcerts 2>/dev/null > "$tmp/ex.txt"
python3 - "$tmp" "$HOST" <<'PY'
import sys,re,subprocess
t,host=sys.argv[1],sys.argv[2]
blocks=re.findall(r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----",open(f"{t}/ex.txt").read(),re.S)
ders=[]
for i,b in enumerate(blocks):
    open(f"{t}/c{i}.pem","w").write(b+"\n")
    subprocess.run(["openssl","x509","-in",f"{t}/c{i}.pem","-outform","DER","-out",f"{t}/c{i}.der"],check=True)
    ders.append(f"{t}/c{i}.der")
o="// GENERATED by tools/gen_ca_testvec.sh — real chain for net::x509 tests.\n"
names=[]
for i,d in enumerate(ders):
    o+=f"static C{i}: &[u8] = &[{','.join(str(b) for b in open(d,'rb').read())}];\n"; names.append(f"C{i}")
o+=f"static TEST_CHAIN: [&[u8]; {len(names)}] = [{', '.join(names)}];\n"
o+=f'static TEST_HOST: &str = "{host}";\n'
o+="static TEST_NOW: u64 = 1783622246; // FIX to a time inside the leaf validity window\n"
open("kernel/src/net/ca_testvec.rs","w").write(o)
print(f"wrote ca_testvec.rs ({len(names)} certs) — CHECK TEST_NOW is inside validity")
PY
rm -rf "$tmp"
