#!/usr/bin/env python3
"""Generate kernel/src/cortex/iq_tables.rs from llama.cpp's ggml-common.h.

The i-quant formats (IQ2_XXS/XS/S, IQ3_XXS/S, IQ4_NL/XS) decode through fixed
codebook/grid lookup tables defined in ggml-common.h. This script extracts
them verbatim and emits a no_std Rust module, so the kernel's dequant is
byte-identical to ggml's by construction.

Usage:
    curl -sL -o /tmp/ggml-common.h \
      https://raw.githubusercontent.com/ggml-org/llama.cpp/master/ggml/src/ggml-common.h
    python3 tools/gen_iq_tables.py /tmp/ggml-common.h > kernel/src/cortex/iq_tables.rs
"""

import re
import sys

# (name, c_type, rust_type, expected_len)
TABLES = [
    ("kmask_iq2xs", "uint8_t", "u8", 8),
    ("ksigns_iq2xs", "uint8_t", "u8", 128),
    ("iq2xxs_grid", "uint64_t", "u64", 256),
    ("iq2xs_grid", "uint64_t", "u64", 512),
    ("iq2s_grid", "uint64_t", "u64", 1024),
    ("iq3xxs_grid", "uint32_t", "u32", 256),
    ("iq3s_grid", "uint32_t", "u32", 512),
    ("kvalues_iq4nl", "int8_t", "i8", 16),
]


def main(path):
    src = open(path).read()
    print("//! GENERATED by tools/gen_iq_tables.py from llama.cpp ggml-common.h")
    print("//! -- do not edit by hand. The i-quant codebook/grid tables, verbatim,")
    print("//! so IQ2/IQ3/IQ4 dequantization is byte-identical to ggml's.")
    print("#![allow(clippy::all)]")
    print()
    for name, ctype, rtype, want in TABLES:
        m = re.search(
            r"GGML_TABLE_BEGIN\(" + ctype + r", " + name + r", \w+\)(.*?)GGML_TABLE_END\(\)",
            src,
            re.S,
        )
        if not m:
            sys.exit(f"table {name} not found")
        vals = re.findall(r"(0x[0-9a-fA-F]+|-?\d+)", m.group(1))
        if len(vals) != want:
            sys.exit(f"table {name}: expected {want} values, found {len(vals)}")
        print(f"pub static {name.upper()}: [{rtype}; {want}] = [")
        for i in range(0, len(vals), 8):
            print("    " + ", ".join(vals[i : i + 8]) + ",")
        print("];")
        print()


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else sys.exit(__doc__))
