#!/usr/bin/env python3
"""Phase 3 host reference (CHITTI_OS_HANDOFF.md Part 2: numerics validated
against a NumPy reference). Generates deterministic test vectors for each
Cortex tensor kernel and their float32 reference outputs, emitting
kernel/src/cortex/testdata.rs. The in-kernel `cargo test` compares each
kernel's output to these consts within a stated tolerance, so the kernels
are validated BEFORE they are assembled into the forward pass.

Self-consistency note: for the quantized kernels we emit the raw GGUF block
bytes AND compute the reference by dequantizing *those same bytes* in NumPy
with the identical d*(q) / d*(nibble-8) formula. So the test checks the
kernel against an independent NumPy implementation processing byte-identical
input -- exactly the parity check the handoff mandates.
"""
import numpy as np

np.random.seed(0xC0FFEE)

QK = 32


def fmt_f32(x):
    # np.float32 -> python float is exact; repr round-trips through Rust's
    # f32 literal parser back to the same f32.
    return repr(float(np.float32(x)))


def f32_array(name, arr):
    arr = np.asarray(arr, dtype=np.float32).ravel()
    body = ", ".join(fmt_f32(v) for v in arr)
    return f"pub static {name}: [f32; {arr.size}] = [{body}];\n"


def u8_array(name, arr):
    arr = np.asarray(arr, dtype=np.uint8).ravel()
    body = ", ".join(str(int(v)) for v in arr)
    return f"pub static {name}: [u8; {arr.size}] = [{body}];\n"


def usize_const(name, v):
    return f"pub const {name}: usize = {int(v)};\n"


def f32_const(name, v):
    return f"pub const {name}: f32 = {fmt_f32(v)};\n"


# --- Q8_0 quantize / dequant (llama.cpp block_q8_0 layout) ----------------
def quantize_q8_0(x):
    """x: (nblocks*QK,) float -> raw bytes (nblocks * 34)."""
    x = x.reshape(-1, QK).astype(np.float32)
    out = bytearray()
    for blk in x:
        amax = np.max(np.abs(blk))
        d = np.float32(amax / 127.0) if amax > 0 else np.float32(0.0)
        inv = np.float32(1.0 / d) if d > 0 else np.float32(0.0)
        q = np.clip(np.round(blk * inv), -127, 127).astype(np.int8)
        out += np.float16(d).tobytes()
        out += q.tobytes()
    return bytes(out)


def dequant_q8_0(raw):
    n = len(raw) // 34
    out = np.empty(n * QK, dtype=np.float32)
    for b in range(n):
        base = b * 34
        d = np.frombuffer(raw[base:base + 2], dtype=np.float16)[0].astype(np.float32)
        q = np.frombuffer(raw[base + 2:base + 34], dtype=np.int8).astype(np.float32)
        out[b * QK:(b + 1) * QK] = d * q
    return out


# --- Q4_0 quantize / dequant (llama.cpp block_q4_0 layout) ----------------
def quantize_q4_0(x):
    x = x.reshape(-1, QK).astype(np.float32)
    out = bytearray()
    for blk in x:
        idx = int(np.argmax(np.abs(blk)))
        maxv = np.float32(blk[idx])
        d = np.float32(maxv / -8.0)
        inv = np.float32(1.0 / d) if d != 0 else np.float32(0.0)
        qs = bytearray(QK // 2)
        for j in range(QK // 2):
            x0 = int(min(15, int(blk[j] * inv + 8.5)))
            x1 = int(min(15, int(blk[j + QK // 2] * inv + 8.5)))
            x0 = max(0, x0)
            x1 = max(0, x1)
            qs[j] = x0 | (x1 << 4)
        out += np.float16(d).tobytes()
        out += bytes(qs)
    return bytes(out)


def dequant_q4_0(raw):
    n = len(raw) // 18
    out = np.empty(n * QK, dtype=np.float32)
    for b in range(n):
        base = b * 18
        d = np.frombuffer(raw[base:base + 2], dtype=np.float16)[0].astype(np.float32)
        for j in range(QK // 2):
            byte = raw[base + 2 + j]
            lo = (byte & 0x0F) - 8
            hi = (byte >> 4) - 8
            out[b * QK + j] = d * np.float32(lo)
            out[b * QK + j + QK // 2] = d * np.float32(hi)
    return out


chunks = []
chunks.append("//! GENERATED by tools/ref.py -- do not edit by hand.\n")
chunks.append("//! Float32 reference vectors (NumPy) for the Cortex tensor kernels.\n")
chunks.append("#![allow(clippy::all)]\n\n")

# --- Q8_0 single block ----------------------------------------------------
blk = np.random.randn(QK).astype(np.float32) * 3.0
raw = quantize_q8_0(blk)
chunks.append(u8_array("Q8_0_BLOCK", np.frombuffer(raw, dtype=np.uint8)))
chunks.append(f32_array("Q8_0_EXPECTED", dequant_q8_0(raw)))

# --- Q4_0 single block ----------------------------------------------------
blk = np.random.randn(QK).astype(np.float32) * 2.0
raw = quantize_q4_0(blk)
chunks.append(u8_array("Q4_0_BLOCK", np.frombuffer(raw, dtype=np.uint8)))
chunks.append(f32_array("Q4_0_EXPECTED", dequant_q4_0(raw)))

# --- matvec Q8_0 ----------------------------------------------------------
rows, cols = 8, 64
W = (np.random.randn(rows, cols).astype(np.float32) * 0.5)
raw = quantize_q8_0(W.ravel())
Wdq = dequant_q8_0(raw).reshape(rows, cols)
x = np.random.randn(cols).astype(np.float32)
y = (Wdq.astype(np.float32) @ x.astype(np.float32)).astype(np.float32)
chunks.append(usize_const("MV_Q8_ROWS", rows))
chunks.append(usize_const("MV_Q8_COLS", cols))
chunks.append(u8_array("MV_Q8_W", np.frombuffer(raw, dtype=np.uint8)))
chunks.append(f32_array("MV_Q8_X", x))
chunks.append(f32_array("MV_Q8_Y", y))

# --- matvec Q4_0 ----------------------------------------------------------
raw = quantize_q4_0(W.ravel())
Wdq = dequant_q4_0(raw).reshape(rows, cols)
y = (Wdq.astype(np.float32) @ x.astype(np.float32)).astype(np.float32)
chunks.append(usize_const("MV_Q4_ROWS", rows))
chunks.append(usize_const("MV_Q4_COLS", cols))
chunks.append(u8_array("MV_Q4_W", np.frombuffer(raw, dtype=np.uint8)))
chunks.append(f32_array("MV_Q4_X", x))
chunks.append(f32_array("MV_Q4_Y", y))

# --- rmsnorm --------------------------------------------------------------
n = 128
rx = np.random.randn(n).astype(np.float32)
rw = (np.random.randn(n).astype(np.float32) * 0.3 + 1.0)
eps = np.float32(1e-6)
ss = np.float32(np.mean(rx.astype(np.float32) ** 2))
scale = np.float32(1.0 / np.sqrt(ss + eps))
ry = (rx * scale * rw).astype(np.float32)
chunks.append(f32_array("RMS_X", rx))
chunks.append(f32_array("RMS_W", rw))
chunks.append(f32_const("RMS_EPS", eps))
chunks.append(f32_array("RMS_Y", ry))

# --- rope (NeoX / rotate_half, Qwen2 theta=1e6) ---------------------------
head_dim = 64
pos = 7
theta = np.float32(1_000_000.0)
rin = np.random.randn(head_dim).astype(np.float32)
half = head_dim // 2
rout = rin.copy().astype(np.float32)
for i in range(half):
    freq = np.float32(1.0 / (float(theta) ** (float(2 * i) / head_dim)))
    angle = np.float32(pos * freq)
    c = np.float32(np.cos(angle))
    s = np.float32(np.sin(angle))
    a = np.float32(rin[i])
    b = np.float32(rin[i + half])
    rout[i] = np.float32(a * c - b * s)
    rout[i + half] = np.float32(b * c + a * s)
chunks.append(usize_const("ROPE_HEAD_DIM", head_dim))
chunks.append(usize_const("ROPE_POS", pos))
chunks.append(f32_const("ROPE_THETA", theta))
chunks.append(f32_array("ROPE_IN", rin))
chunks.append(f32_array("ROPE_OUT", rout))

# --- softmax --------------------------------------------------------------
sx = (np.random.randn(50).astype(np.float32) * 4.0)
m = np.max(sx)
e = np.exp((sx - m).astype(np.float32)).astype(np.float32)
so = (e / np.sum(e, dtype=np.float32)).astype(np.float32)
chunks.append(f32_array("SOFTMAX_IN", sx))
chunks.append(f32_array("SOFTMAX_OUT", so))

# --- silu_mul (SwiGLU) ----------------------------------------------------
g = np.random.randn(96).astype(np.float32)
u = np.random.randn(96).astype(np.float32)
sig = (g / (1.0 + np.exp(-g.astype(np.float32)))).astype(np.float32)
smo = (sig * u).astype(np.float32)
chunks.append(f32_array("SILU_GATE", g))
chunks.append(f32_array("SILU_UP", u))
chunks.append(f32_array("SILU_OUT", smo))

out_path = "kernel/src/cortex/testdata.rs"
with open(out_path, "w") as f:
    f.write("".join(chunks))
print(f"wrote {out_path} ({len(chunks)} sections)")
