//! Continuous-batching token scheduler (`CHITTI_OS_HANDOFF.md` Phase 3's
//! `cortex/sched.rs` role). Several agents, each with its own KV cache and
//! decode state, are advanced in **interleaved** forward passes: one round
//! steps every still-active stream by one token, so N agents make progress
//! concurrently rather than one running to completion before the next
//! starts. This is the token-level analogue of the Phase 2 task scheduler
//! (round-robin, one "quantum" = one token here), and is what a later
//! continuous-batching inference server would drive from the async executor.
//!
//! Phase 3 keeps it single-threaded and deterministic; hooking it to the
//! Phase 2 scheduler's preemption is deferred (the phase spec's "Do NOT
//! yet" list covers inference/scheduler integration beyond this).

use super::model::{argmax, Model, State};
use super::model::Cache;
use super::sampler::{sample, Grammar, Rng};
use alloc::vec::Vec;

/// One in-flight decode stream (an "agent" at the token level).
pub struct Stream {
    kv: Cache,
    state: State,
    pos: usize,
    /// Full token sequence: prompt followed by everything generated.
    pub tokens: Vec<usize>,
    to_generate: usize,
    pub done: bool,
}

pub struct Batch<'a> {
    model: &'a Model<'a>,
    pub streams: Vec<Stream>,
    /// Records the order streams were stepped in, for the interleaving
    /// assertion in the acceptance test.
    pub step_order: Vec<usize>,
}

impl<'a> Batch<'a> {
    pub fn new(model: &'a Model<'a>) -> Self {
        Self { model, streams: Vec::new(), step_order: Vec::new() }
    }

    /// Add a stream: prefill `prompt` (writing its KV) and queue up
    /// `generate` tokens to be produced during batched stepping.
    pub fn add_stream(&mut self, prompt: &[usize], generate: usize) -> usize {
        let mut kv = self.model.new_cache();
        let mut state = self.model.new_state();
        let mut tokens = Vec::with_capacity(prompt.len() + generate);
        for (pos, &tok) in prompt.iter().enumerate() {
            self.model.forward(tok, pos, &mut kv, &mut state, pos + 1 == prompt.len());
            tokens.push(tok);
        }
        let id = self.streams.len();
        self.streams.push(Stream { kv, state, pos: prompt.len(), tokens, to_generate: generate, done: generate == 0 });
        id
    }

    /// Advance one stream by exactly one token (greedy, or sampled if a
    /// `rng`/`grammar` is supplied). Returns the token, or `None` if the
    /// stream is already finished.
    fn step_stream(
        &mut self,
        id: usize,
        temperature: f32,
        rng: Option<&mut Rng>,
        grammar: Option<&dyn Grammar>,
    ) -> Option<usize> {
        let model = self.model;
        let s = &mut self.streams[id];
        if s.done {
            return None;
        }
        // The last token in the sequence is the input for this step; its
        // logits are already in `s.state` (from prefill or the prior step).
        let next = match rng {
            Some(r) => sample(&mut s.state.logits, temperature, r, grammar),
            None => argmax(&s.state.logits),
        };
        model.forward(next, s.pos, &mut s.kv, &mut s.state, true);
        s.pos += 1;
        s.tokens.push(next);
        s.to_generate -= 1;
        if s.to_generate == 0 {
            s.done = true;
        }
        Some(next)
    }

    /// Run all streams to completion in interleaved rounds: each round
    /// steps every not-yet-done stream once. Greedy decoding (temp 0).
    pub fn run_greedy(&mut self) {
        while self.streams.iter().any(|s| !s.done) {
            for id in 0..self.streams.len() {
                if !self.streams[id].done {
                    self.step_stream(id, 0.0, None, None);
                    self.step_order.push(id);
                }
            }
        }
    }

    /// The tokens generated by stream `id` after its prompt.
    pub fn generated(&self, id: usize, prompt_len: usize) -> &[usize] {
        &self.streams[id].tokens[prompt_len..]
    }
}
