//! Greedy-parity reference fixtures for the acceptance gate, keyed by the
//! model's `general.name` — so `ref-check` works for whichever GGUF is booted
//! (`-model`), and a model with no fixture still runs the self-consistency
//! checks (parity reports SKIP).
//!
//! GENERATED by `tools/cortexdiff` (the host harness that mounts the kernel's
//! own cortex engine — same parser, kernels, and forward pass, seconds per
//! run). Regenerate a fixture with:
//!
//!   cargo run --release --manifest-path tools/cortexdiff/Cargo.toml -- \
//!       greedy <model.gguf> "hello whats your name?" 8
//!
//! and copy the printed `continuation_ids`. Cross-check the same file against
//! llama.cpp with `tools/cortexdiff/diff.py` before committing a fixture.

/// The fixed reference prompt, encoded at runtime by the loaded model's own
/// tokenizer (which also exercises the tokenizer per family).
pub const PROMPT: &str = "hello whats your name?";

/// A per-model greedy continuation of [`PROMPT`].
pub struct Fixture {
    /// `general.name` of the GGUF this fixture was generated from.
    pub name: &'static str,
    /// Greedy continuation ids (temperature 0) following the encoded prompt.
    pub expected: &'static [u32],
}

pub static FIXTURES: &[Fixture] = &[
    Fixture { name: "Qwen3.5-0.8B", expected: &[271, 248068, 271, 248069, 271, 4888, 803, 369] },
    Fixture { name: "Qwen3.5-4B", expected: &[271, 248068, 198, 90700, 8340, 25, 271, 16] },
];

/// The fixture for the loaded model, by its `general.name` (None → SKIP).
pub fn for_model(name: Option<&str>) -> Option<&'static Fixture> {
    let n = name?;
    FIXTURES.iter().find(|f| f.name == n)
}
