//! GENERATED by tools/ref_qwen35.py -- do not edit by hand.
//! Fixed prompt + greedy reference continuation for the Qwen3.5-0.8B
//! Phase 3 parity gate (`cargo xtask ref-check`) and the boot-time demo.
pub const PROMPT: &str = "hello whats your name?";
pub static PROMPT_IDS: [u32; 4] = [14556, 38777, 678, 803];
pub static EXPECTED_CONTINUATION: [u32; 8] = [30, 271, 248068, 271, 248069, 271, 4888, 803];
pub const PROMPT_FINAL_ARGMAX: u32 = 30;
pub const PROMPT_FINAL_LOGIT: f32 = 16.39484405517578;
