//! **Sample files** — the `/samples/` corpus a freshly booted machine can open
//! without a network, a disk, or a single downloaded byte.
//!
//! An OS whose media stack is most of its interesting code (PNG/JPEG in ring 3,
//! H.264 + AAC, MP3, WAV, PDF-via-wasm, the editor's highlighters) is awkward to
//! *try*: every one of those paths needs a file, and on a fresh boot there are
//! none, so the first thing anyone does is `/http -O` something. This module is
//! the answer: a small corpus is embedded in the kernel image at build time and
//! written into the Synapse store at boot, landing at
//!
//! ```text
//! /samples/images/   png + jpeg (rgb, rgba, grayscale)
//! /samples/videos/   h.264 + aac in mp4
//! /samples/audios/   wav, mp3 (with an id3 tag), adts aac
//! /samples/misc/     pdf, txt, json, csv, html
//! /samples/js/       scripts for the in-kernel `/js` CLI (authored in-tree)
//! ```
//!
//! so `/open /samples/images/fruits.jpg` works on the first boot.
//!
//! **Nothing is embedded by default.** The corpus is fetched by
//! `cargo xtask sample-files` into the gitignored `assets/samples/` and embedded
//! only when `CHITTI_SAMPLE_FILES` asks for it — `make run` and `make vbox` set
//! it, `cargo xtask build` on a fresh clone does not. So a CI build, the unit
//! suite, and anyone who never asked for samples get a byte-identical kernel to
//! before, and `EMBEDDED` below is an empty slice.
//!
//! Three things this deliberately does *not* do:
//!
//! - **It does not overwrite.** Seeding skips any path that already exists, so a
//!   sample edited on an installed (ext4-backed) system stays edited across
//!   reboots — the store is durable there, and re-seeding on every boot would
//!   silently revert a user's file.
//! - **It writes untagged**, exactly as a bundled agent asset does
//!   ([`crate::skills::package::SkillPackage::place_agent_home`]): these bytes
//!   arrive at build time from a source the operator chose, not from a runtime
//!   ingest. Reading one into an agent's context still taints that context by the
//!   normal read path, which is where the taint actually matters.
//! - **It defines no corpus of its own.** `xtask` owns the file list (URLs,
//!   provenance, licences); `kernel/build.rs` walks the directory. A table here
//!   would be a second copy to drift out of sync.

use alloc::string::String;
use alloc::vec::Vec;

// `EMBEDDED`: the corpus, as `(category, filename, bytes)`. Generated by
// `kernel/build.rs` from `assets/samples/`; a category of `""` means the file
// sits at the root of `/samples/` (the fetch's own `README.md`, which records
// where each file came from and under what licence).
//
// A plain comment, not a doc comment: rustdoc cannot document what a macro
// invocation expands to, so `///` here is only a warning.
#[cfg(samples_embedded)]
include!(concat!(env!("OUT_DIR"), "/samples.rs"));

/// No corpus was requested or none was on disk at build time.
#[cfg(not(samples_embedded))]
pub static EMBEDDED: &[(&str, &str, &[u8])] = &[];

/// Where the corpus lands in the store.
pub const ROOT: &str = "/samples";

/// The store path for one corpus entry. A category of `""` puts the file at the
/// root of [`ROOT`]; anything else nests one level.
///
/// Pure so the layout is testable without a store: the paths are what `/open`
/// and `ls` are given, and an off-by-one slash here is a corpus nothing can
/// find.
pub fn store_path(category: &str, name: &str) -> String {
    let cat = category.trim_matches('/');
    if cat.is_empty() {
        alloc::format!("{ROOT}/{name}")
    } else {
        alloc::format!("{ROOT}/{cat}/{name}")
    }
}

/// Decide what seeding would write: every entry whose store path is absent,
/// paired with its bytes, plus the number skipped because it was already there.
///
/// Split out from [`seed`] so the "never overwrite" rule — the one that keeps a
/// reboot from reverting an edited sample on a durable store — is checkable
/// without a filesystem.
pub fn seed_plan<'a, F: Fn(&str) -> bool>(
    entries: &'a [(&'a str, &'a str, &'a [u8])],
    exists: F,
) -> (Vec<(String, &'a [u8])>, usize) {
    let mut write = Vec::new();
    let mut skipped = 0usize;
    for (cat, name, bytes) in entries {
        let path = store_path(cat, name);
        if exists(&path) {
            skipped += 1;
        } else {
            write.push((path, *bytes));
        }
    }
    (write, skipped)
}

/// Write the embedded corpus into the Synapse store, skipping files that are
/// already there. A no-op (and silent) when nothing is embedded.
///
/// Called from the boot path **after** the persistent store is mounted, so on an
/// installed system the samples land on the ext4 data partition once and are
/// skipped on every later boot.
pub fn seed() {
    if EMBEDDED.is_empty() {
        return;
    }
    let (writes, skipped) = seed_plan(EMBEDDED, crate::synapse::fs::exists);
    let bytes: usize = writes.iter().map(|(_, b)| b.len()).sum();
    let written = writes.len();
    for (path, contents) in writes {
        crate::synapse::fs::write(&path, contents);
    }
    crate::ktrace::log_fmt(format_args!(
        "samples: {} file(s) seeded under {ROOT}/ ({} KiB), {} already present",
        written,
        bytes / 1024,
        skipped
    ));
}

/// One line per category with a file count and total size — what `/samples`
/// prints. Pure over the embedded table so the summary is testable.
pub fn summary() -> Vec<(String, usize, usize)> {
    let mut out: Vec<(String, usize, usize)> = Vec::new();
    for (cat, _, bytes) in EMBEDDED {
        let key = if cat.is_empty() { ROOT } else { *cat };
        match out.iter_mut().find(|(c, _, _)| c == key) {
            Some((_, n, b)) => {
                *n += 1;
                *b += bytes.len();
            }
            None => out.push((String::from(key), 1, bytes.len())),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    #[test_case]
    fn store_path_nests_one_level_and_roots_an_empty_category() {
        assert_eq!(store_path("images", "a.png"), "/samples/images/a.png");
        assert_eq!(store_path("", "README.md"), "/samples/README.md");
        // A category with stray slashes must not produce `//`, which normalises
        // to a different key than the one `/open` would be given.
        assert_eq!(store_path("/videos/", "c.mp4"), "/samples/videos/c.mp4");
    }

    #[test_case]
    fn seed_plan_skips_what_is_already_in_the_store() {
        let entries: &[(&str, &str, &[u8])] = &[
            ("images", "a.png", b"png"),
            ("audios", "b.wav", b"wav"),
            ("", "README.md", b"docs"),
        ];
        // `b.wav` is already there — an installed system on its second boot,
        // possibly with the user's own edits in it.
        let (writes, skipped) = seed_plan(entries, |p| p == "/samples/audios/b.wav");
        assert_eq!(skipped, 1);
        assert_eq!(
            writes.iter().map(|(p, _)| p.as_str()).collect::<Vec<_>>(),
            vec!["/samples/images/a.png", "/samples/README.md"]
        );
        // Nothing to do once everything exists: a reboot must not rewrite.
        let (writes, skipped) = seed_plan(entries, |_| true);
        assert!(writes.is_empty());
        assert_eq!(skipped, entries.len());
    }

    #[test_case]
    fn seeding_is_idempotent_against_the_real_store() {
        let entries: &[(&str, &str, &[u8])] = &[("images", "seed_test.png", b"\x89PNG")];
        let (writes, _) = seed_plan(entries, crate::synapse::fs::exists);
        for (p, b) in &writes {
            crate::synapse::fs::write(p, b);
        }
        assert_eq!(
            crate::synapse::fs::read("/samples/images/seed_test.png").as_deref(),
            Some(&b"\x89PNG"[..])
        );
        // Second pass: the plan is empty, so an edit made in between survives.
        crate::synapse::fs::write("/samples/images/seed_test.png", b"edited");
        let (writes, skipped) = seed_plan(entries, crate::synapse::fs::exists);
        assert!(writes.is_empty());
        assert_eq!(skipped, 1);
        assert_eq!(
            crate::synapse::fs::read("/samples/images/seed_test.png").as_deref(),
            Some(&b"edited"[..])
        );
        let _ = crate::synapse::fs::remove("/samples/images/seed_test.png", false);
    }

    /// Without `CHITTI_SAMPLE_FILES` there must be no corpus at all — the
    /// default build is the one CI and the unit suite compile.
    #[test_case]
    fn an_unrequested_build_embeds_nothing() {
        #[cfg(not(samples_embedded))]
        assert!(EMBEDDED.is_empty());
        // With samples embedded, every entry must be non-empty and openable by
        // path — an empty file would be a truncated download baked into the image.
        #[cfg(samples_embedded)]
        for (cat, name, bytes) in EMBEDDED {
            assert!(!bytes.is_empty(), "{cat}/{name} is empty");
            assert!(!name.is_empty() && !name.contains('/'), "bad sample name {name:?}");
        }
    }
}
