#!/usr/bin/env python3
"""Regenerate arxiv-metadata.txt -- the whole submission form -- from main.tex.

The submission form's abstract and the paper's abstract must say the same thing,
and the only way to guarantee that is to derive one from the other. arXiv rejects
abstracts over 1920 characters and accepts ASCII only, so this also enforces both
rather than leaving them to be discovered at upload time.
"""
import re
import sys

TITLE = ("The Determinism Boundary: An Operating-System Capability ABI "
         "for Agents as the Unit of Execution")
LIMIT = 1920

DOC = """arXiv submission metadata
=========================
GENERATED by `make arxiv-meta` from main.tex -- do not edit by hand, or the form
and the paper will drift. Everything below is ASCII and within arXiv's limits.

TITLE ({tlen} chars)
-----
{title}

  Checked: not all-caps, no Unicode, no cryptic macros left to expand.

ABSTRACT ({alen} chars; arXiv rejects over {limit})
--------
{abstract}

  Checked: ASCII only; no ~ \\, or font commands; no URLs (arXiv does not
  linkify them in abstracts); em dashes written as `--`. Derived from the LaTeX
  abstract, so the form and the PDF cannot disagree.

CATEGORIES
----------
  Primary:    cs.OS  (Operating Systems)
  Cross-list: cs.CR  (Cryptography and Security)
              cs.AI  (Artificial Intelligence)

  cs.OS is primary because the contribution is a syscall-layer mechanism, not a
  model or an attack. cs.CR is where the injection-defence audience reads.

LICENSE
-------
  Recommended: CC BY 4.0 -- it matches the artifact's Apache-2.0 posture and
  permits the reuse an artifact paper wants. arXiv's default minimal licence
  also works but blocks redistribution. The author's call, and arXiv cannot
  change it after announcement.

BEFORE YOU UPLOAD
-----------------
  1. make arxiv                 -> builds and checks arxiv-submission.tar.gz
  2. Make the repo public (or drop the artifact citation) -- see README.
  3. Tag the release and name the tag in section 4 and refs.bib.
  4. arXiv rebuilds the PDF from source: check THEIR output, not yours, before
     clicking submit. It is a required step and the last chance to catch a
     figure that moved.
  5. New submitters may need an endorsement for cs.OS.
"""


def plain_abstract(tex: str) -> str:
    a = tex[tex.index(r'\begin{abstract}') + 16: tex.index(r'\end{abstract}')]
    a = re.sub(r'\\(syn|os)\{\}', lambda m: 'Synapse' if m.group(1) == 'syn' else 'ChittiOS', a)
    for pat in (r'\\emph\{([^}]*)\}', r'\\textbf\{([^}]*)\}', r'\\code\{([^}]*)\}'):
        a = re.sub(pat, r'\1', a)
    a = (a.replace(r'\,', ' ').replace(r'$\mu$', 'u')
          .replace(r'$3\times10^{-5}$', '3e-5').replace('---', '--').replace(r'\_', '_'))
    return re.sub(r'\s+', ' ', a).strip()


def main() -> int:
    abstract = plain_abstract(open('main.tex').read())
    problems = []
    if len(abstract) > LIMIT:
        problems.append(f"abstract is {len(abstract)} chars; arXiv rejects over {LIMIT}")
    if not abstract.isascii():
        bad = sorted({c for c in abstract if not c.isascii()})
        problems.append(f"non-ASCII in abstract: {bad}")
    if not TITLE.isascii():
        problems.append("non-ASCII in title")
    if TITLE.isupper():
        problems.append("title is all caps")
    for p in problems:
        print(f"arxiv-meta: FAIL {p}", file=sys.stderr)
    if problems:
        return 1
    open('arxiv-metadata.txt', 'w').write(DOC.format(
        title=TITLE, tlen=len(TITLE), abstract=abstract, alen=len(abstract), limit=LIMIT))
    print(f"arxiv-meta: title {len(TITLE)} chars, abstract {len(abstract)}/{LIMIT} "
          f"({LIMIT - len(abstract)} to spare), ASCII clean -> arxiv-metadata.txt")
    return 0


if __name__ == "__main__":
    sys.exit(main())
